---

# Local Lab Devices
#sw06:
#  hostname: 10.1.10.216
#  groups: ['uwaco_network']
##
#weddell-sw02:
#  hostname: 10.1.10.212
#  groups: ['uwaco_network']
#
#arctic-ds01-as01:
#  hostname: 10.1.10.102
#  groups: ['uwaco_network']

# DevNet Always On Sandbox Devices
sandbox-iosxe-latest-1:
  hostname: sandbox-iosxe-latest-1.cisco.com
  groups: ['sandbox-iosxe-latest-1']
#
#sandbox-iosxe-recomm-1:
#  hostname: sandbox-iosxe-recomm-1.cisco.com
#  groups: ['sandbox-iosxe-recomm-1']
